apiVersion: v2
name: java-instrumentation
description: Java instrumentation
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
- name: raw
  version: 2.0.0
  repository: "https://bedag.github.io/helm-charts/"
