raw:
  resources:
  - apiVersion: opentelemetry.io/v1alpha1
    kind: Instrumentation
    metadata:
      name: otel-java-instrumentation
      namespace: telescope
    spec:
      exporter:
        endpoint: http://otel-collector.infra.svc.cluster.local:4317
      propagators:
        - tracecontext
        - baggage
        - b3
      sampler:
        type: parentbased_traceidratio
        argument: "0.25"
      java:
        env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://otel-collector.infra.svc.cluster.local:4317
